### ISSUE TITLE
¿Como saber el orden de los flags en bash?

### ISSUE THREAD

**Issue by gabymandrade** [u-genoma/BioinfinvRepro#11]
# ¿Como saber el orden de los flags en bash?

Escribe el comando para enlistar el contenido de Unidad1/Prac_Uni1/Maiz por tamaño del archivo y haz que el tamaño del archivo se lea en KB y MB (ie reducido en vez de todos los bytes).

```{bash} 
ls -lSh
```

En este ejemplo hacemos primero un list, posteriormente va lSh, este comando tardé tiempo en sacarlo, no si hay una guía para saber como poner en el orden adecuado las opciones en el comando

**Comment by VeroIarrachtai** [comment]
Hola Gaby,
el orden de las flags cuando se utiliza cualquier comando en bash es indistinto.

**Comment by camillethuyentruong** [comment]
`ls` es el comando mientras `-lSh` es una opción dentro de ese comando, por eso se necesita llamar el comando primero. Después,  como dice Vero, el orden de los flags de un comando no importa.
