### ISSUE TITLE
Dudas VCFtools

### ISSUE THREAD

**Issue by BarCS** [u-genoma/BioinfinvRepro#13]
Hola, tengo algunas dudas respecto a VCFTools:
1. ¿La variable se hace solo una vez para luego usar el comando `$vcftools`, o en cada sesión se debe volver a hacer?
2. ¿el wd de la variable debe ser en donde están los datos, ósea data?

**Comment by AliciaMstt** [comment]
la variable se hace dentro del script donde se corre vcftools, así no hay que hacerla en cada sesión, sino que es parte del script.

2. sí.

**Comment by BarCS** [comment]
Gracias
