### ISSUE TITLE
Duda plink

### ISSUE THREAD

**Issue by BarCS** [u-genoma/BioinfinvRepro#14]
Hola,

Cada vez que se utiliza plink debe bajarse a la carpeta bin del wd en el que se trabaja, o si ya lo bajaste a otra carpeta bin de un wd distinto, puede indicarse la ruta relativa para que corra?

**Comment by AliciaMstt** [comment]
puedes poner plink en el bin del wd donde se trabaja, o alternativamente hacer que tu PATH vea otra carpeta donde esté guardado, como hicimos en clase cuando lo pusimos en home.

**Comment by BarCS** [comment]
ok. Gracias.
