### ISSUE TITLE
Duda wget en el Proyecto

### ISSUE THREAD

**Issue by BarCS** [u-genoma/BioinfinvRepro#15]
Hola,

1. ¿si bajo los datos con wget y después utilizo Docker, vuelve a descargar el archivo?, estoy un poco confundida con esto :S
2. ¿La ruta para hacer el contenedor con Docker debe hacerse hacia "data"?

**Comment by AliciaMstt** [comment]
los archivos solo se bajan cuando ocupes wget, independientemtne de si lo haces fuera o dentro de Docker.

La ruta sí es hacia data

**Comment by BarCS** [comment]
Gracias.
