### ISSUE TITLE
Enviar información del Cluster al Github

### ISSUE THREAD

**Issue by BarCS** [u-genoma/BioinfinvRepro#16]
Hola:

No supe cómo mandar una carpeta desde cluster hacia Github. ¿Se tiene que bajar a la computadora con `scp` y después con `git add`, `git commit`y `git push`, o hay una manera de hacerlo directamente del cluster a Github?

**Comment by AliciaMstt** [comment]
puedes configurar github en el cluster igual que hicimos en la compu local

**Comment by BarCS** [comment]
ok. Gracias.
