### ISSUE TITLE
Problema para instalar SNPRelate

### ISSUE THREAD

**Issue by BarCS** [u-genoma/BioinfinvRepro#17]
Hola,
Para hacer el PCA en R traté de instalar SNPRelate y me dice que no está disponible para R 3.6.2. Revisé la versión que necesita SNPRelate y encontré que 3.6.0 pero no encuentro por ningún lado esa versión :(

**Comment by AliciaMstt** [comment]
Me parece que ya te respondieron en gitter, correct?

**Comment by BarCS** [comment]
Sí, ya lo tengo, gracias.
