### ISSUE TITLE
Funcionamiento de grep -oE y construcción de loops

### ISSUE THREAD

**Issue by BarCS** [u-genoma/BioinfinvRepro#7]
#**Grep**

## En general, no me queda del todo claro la creación de las expresiones regulares, ni la diferencia de poner o no -E.

#**loops**

## Me gustaría saber la "lectura" de un loop para tener más claro qué es cada elemento que lo constituye.

**Comment by camillethuyentruong** [comment]
`-e` significa "error exit". Si hay un error dentro de un script, se termina.

**Comment by camillethuyentruong** [comment]
Cuando uno hace un loop, tiene que definir la variable que va a ser repetida en el loop:

`for i in 2 3 4 5; do echo "Bienvenidos $i veces"; done`

```
Bienvenidos 2 veces
Bienvenidos 3 veces
Bienvenidos 4 veces
Bienvenidos 5 veces
```

La variable `i` se necesita llamar con `$` para que bash reconoce que es una variable.

Sin el `$`, eso es lo que pasa:
`for i in 2 3 4 5; do echo "Bienvenidos i veces"; done`

```
Bienvenidos i veces
Bienvenidos i veces
Bienvenidos i veces
Bienvenidos i veces
```

**Comment by BarCS** [comment]
Gracias.
