### ISSUE TITLE
Duda cambio de colores de gráfica

### ISSUE THREAD

**Issue by BarCS** [u-genoma/BioinfinvRepro#8]
#**Gráfica con ggplot**

### El código es el siguiente:

```
  ggplot (data=dat, aes(x=size, fill=group, colour=group)) +
  geom_histogram(alpha = 2.5, position = "identity") +
  scale_fill_manual(values=c("green3", "darkblue"))
```

### También quisiera saber, qué indica: **position = "identity"**

**Comment by VeroIarrachtai** [comment]
Hola Barbara,
Para que el contorno y relleno de las barras en tu plot sea el mismo debes utilizar el argumento "fill= ". En este ejemplo colorea de acuerdo a "species"

```
ggplot (data=dat, aes(x=size, fill=species)) +
geom_histogram(alpha = .5, position = "identity") +
scale_fill_manual(values=c("green3", "darkblue"))
```
Por otro lado "position=identity". Ubica el valor del dato exactamente en el lugar de la gráfica que corresponde a su valor.
Tambien puedes checar: https://books.google.com.mx/books?id=vfi3DQAAQBAJ&pg=PA28&lpg=PA28&dq=position+%22identity%22+%22dodge%22&source=bl&ots=c15-LDC3Ca&sig=ACfU3U1Rm2uNs-eRaVW0090UNjeg7BuA0w&hl=es-419&sa=X&ved=2ahUKEwjOiLLY9qnnAhXkk60KHfF0BWkQ6AEwC3oECAoQAQ#v=onepage&q=position%20%22identity%22%20%22dodge%22&f=false

**Comment by BarCS** [comment]
Gracias.
